CC = gcc
CFLAGS = -Wall

all: Part_Bonus_client Part_Bonus_cube Part_Bonus_inetd Part_Bonus_square

Part_Bonus_client:
	$(CC) $(CFLAGS) -o ./client ./client.c

Part_Bonus_cube:
	$(CC) $(CFLAGS) -o ./cube ./cube.c

Part_Bonus_inetd:
	$(CC) $(CFLAGS) -o ./inetd ./inetd.c

Part_Bonus_square:
	$(CC) $(CFLAGS) -o ./square ./square.c

clean:
	rm -f ./client ./cube ./inetd ./square
